//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibaryApp.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBKITABXANAEntities : DbContext
    {
        public DBKITABXANAEntities()
            : base("name=DBKITABXANAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLACTION> TBLACTION { get; set; }
        public virtual DbSet<TBLBOOK> TBLBOOK { get; set; }
        public virtual DbSet<TBLCASH> TBLCASH { get; set; }
        public virtual DbSet<TBLCATEGORY> TBLCATEGORY { get; set; }
        public virtual DbSet<TBLFINE> TBLFINE { get; set; }
        public virtual DbSet<TBLMEMBERS> TBLMEMBERS { get; set; }
        public virtual DbSet<TBLPERSONAL> TBLPERSONAL { get; set; }
        public virtual DbSet<TBLWRITER> TBLWRITER { get; set; }
        public virtual DbSet<TBLCONTACT> TBLCONTACT { get; set; }
        public virtual DbSet<TBLSITEABOUT> TBLSITEABOUT { get; set; }
        public virtual DbSet<TBLMESSAGE> TBLMESSAGE { get; set; }
    
        public virtual ObjectResult<string> BestBookWriter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BestBookWriter");
        }
    
        public virtual ObjectResult<string> BestMemberAction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BestMemberAction");
        }
    
        public virtual ObjectResult<string> BestPersonalAction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BestPersonalAction");
        }
    
        public virtual ObjectResult<string> BestBookAction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BestBookAction");
        }
    }
}
