//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibaryApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBOOK()
        {
            this.TBLACTION = new HashSet<TBLACTION>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<byte> CATEGORY { get; set; }
        public Nullable<int> WRITER { get; set; }
        public string DATE { get; set; }
        public string PUBLISHING { get; set; }
        public string PAGES { get; set; }
        public Nullable<bool> BOOKSTATUS { get; set; }
        public Nullable<bool> SD { get; set; }
        public Nullable<int> STOCK { get; set; }
        public string PHOTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLACTION> TBLACTION { get; set; }
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
        public virtual TBLWRITER TBLWRITER { get; set; }
    }
}
