//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibaryApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMEMBERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMEMBERS()
        {
            this.TBLACTION = new HashSet<TBLACTION>();
            this.TBLFINE = new HashSet<TBLFINE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string MAIL { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FOTO { get; set; }
        public string MOB { get; set; }
        public string SCHOOL { get; set; }
        public Nullable<bool> SD { get; set; }
        public Nullable<bool> CONFIRMATION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLACTION> TBLACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFINE> TBLFINE { get; set; }
    }
}
